paritytech/substrate-connect

projects/burnr/src/App.tsx, projects/burnr/src/components/Head.tsx, projects/burnr/src/components/LogoApp.tsx, projects/burnr/src/components/NodeSelector.tsx, projects/burnr/src/components/NodeSelectorItem.tsx, projects/burnr/src/components/NodeSelectorSelected.tsx, projects/burnr/src/components/index.tsx, projects/burnr/src/contexts/ApiPromiseContext.tsx, projects/burnr/src/hooks/api/useApiCreate.ts, projects/burnr/src/hooks/api/useDidUpdateEffect.ts
Interim solution for node switch.
=> Make switch functional

projects/smoldot-browser-demo/index.html, projects/smoldot-browser-demo/src/index.ts
Poking demo for general understanding.
Changes:
- system fonts
- substrate color
- message timestamps
=> style: smoldot-browser-demo 

projects/smoldot-browser-demo/index.html, projects/smoldot-browser-demo/package.json, projects/smoldot-browser-demo/src/index.ts, projects/smoldot-browser-demo/src/view.ts, projects/smoldot-browser-demo/tsconfig.json
Shows and updates the state of syncing in the UI and improves the messaging to be clearer / more accurate about what's happening and when.   Also adds emojis :tada: to the messages.
We probably don't want to make the UI any more complicated than this without using react!
=> Show chain syncing state in smoldot demo

package.json
change script  "dev:burnr" from "yarn workspace @substrate/connect run dev" to "yarn workspace @substrate/burnr run dev"
=> fix dev:burnr script on main package.json

projects/burnr/src/components/AccountBurn.tsx, projects/burnr/src/components/AccountMenu.tsx, projects/burnr/src/components/NavTabs.tsx, projects/burnr/src/components/index.tsx
Addressing #3. Changes:
- Hide recovery in context menu (keeping it for now to play with accounts while developing)
- Warning when burning keys from account with funds
=> UI Improvements for burning keys

projects/burnr/src/App.tsx, projects/burnr/src/Home.tsx, projects/burnr/src/components/NodeSelector.tsx, projects/burnr/src/hooks/api/useApiCreate.ts
=> Make nodeselector visible and add loader

projects/smoldot-extension/package.json, projects/smoldot-extension/src/components/Options.tsx, projects/smoldot-extension/src/components/Popup.tsx, projects/smoldot-extension/src/components/index.tsx, projects/smoldot-extension/src/options.html, projects/smoldot-extension/src/options.tsx, projects/smoldot-extension/src/popup.html, projects/smoldot-extension/src/popup.ts, projects/smoldot-extension/src/popup.tsx, projects/smoldot-extension/tsconfig.json
=> fix the files and building process for extension

projects/burnr/src/Home.tsx, projects/burnr/src/components/AccountCard.tsx, projects/burnr/src/components/NavTabs.tsx, projects/smoldot-extension/src/assets/manifest.json
=> rm account tab

packages/smoldot-provider/src/SmoldotProvider.test.ts, packages/smoldot-test-utils/.gitignore, packages/smoldot-test-utils/.npmignore, packages/smoldot-test-utils/LICENSE, packages/smoldot-test-utils/README.md, packages/smoldot-test-utils/package.json, packages/smoldot-test-utils/src/index.ts, packages/smoldot-test-utils/tsconfig.json, yarn.lock
We'll need to use these in the extension too so that we can fake smoldot in the tests
=> Move smoldot mocking helpers into a separate package

projects/smoldot-extension/src/assets/fonts/fonts.tsx, projects/smoldot-extension/src/assets/fonts/index.d.ts, projects/smoldot-extension/src/components/AntSwitch.tsx, projects/smoldot-extension/src/components/IconWeb3.tsx, projects/smoldot-extension/src/components/NodeArea.tsx, projects/smoldot-extension/src/components/PolkaFont.tsx, projects/smoldot-extension/src/components/Switch.tsx, projects/smoldot-extension/src/components/TabInfo.tsx, projects/smoldot-extension/src/components/index.tsx, projects/smoldot-extension/src/components/theme.tsx, projects/smoldot-extension/src/containers/Popup.tsx
=> Extension UI tuning

projects/smoldot-extension/src/components/ClientItem.tsx, projects/smoldot-extension/src/components/ClientSearch.tsx, projects/smoldot-extension/src/components/IconWeb3.tsx, projects/smoldot-extension/src/components/Inputs.tsx, projects/smoldot-extension/src/components/Logo.tsx, projects/smoldot-extension/src/components/index.tsx, projects/smoldot-extension/src/containers/Options.tsx, projects/smoldot-extension/src/fonts/fonts.tsx
=> UI components for settings page

yarn.CI.yml
=> create CI and actions

projects/burnr/src/Home.tsx, projects/burnr/src/components/BalanceValue.tsx, projects/burnr/src/components/HistoryTable.tsx, projects/burnr/src/hooks/useBalance.ts
Switch to using BN.js/ Polkadot JS Balance Types instead of `number` or `string`
Closes #51
=> Switch to using BN.js/ Polkadot JS Balance Types

projects/burnr/package.json, projects/burnr/src/components/AccountBurn.tsx, projects/burnr/src/components/InputAddress.tsx, projects/burnr/src/components/InputFunds.tsx, projects/burnr/src/components/SendFundsForm.tsx, projects/burnr/src/utils/utils.ts, yarn.lock
=> Burnr wallet - Fix send functionality

projects/burnr/src/components/BalanceValue.tsx, projects/burnr/src/components/HistoryTable.tsx, projects/burnr/src/components/HistoryTableRow.tsx, projects/burnr/src/components/PopoverExtrinsic.tsx, projects/burnr/src/components/SendFundsForm.tsx, projects/burnr/src/components/index.tsx, projects/burnr/src/utils/types.ts
=> Fix burnr history view

projects/extension/src/components/ClientItem.tsx, projects/extension/src/components/ClientSearch.tsx, projects/extension/src/components/IconWeb3.tsx, projects/extension/src/components/Inputs.tsx, projects/extension/src/components/Switch.tsx, projects/extension/src/components/Tab.tsx, projects/extension/src/components/TabInfo.tsx, projects/extension/src/components/index.tsx, projects/extension/src/components/theme.tsx, projects/extension/src/containers/Popup.tsx, projects/extension/src/hooks/useTabs.tsx, projects/extension/src/types/enums.ts, projects/extension/src/types/index.ts
=> Extension Popup UI polish

packages/connect/src/Detector.ts, packages/connect/src/index.ts, projects/extension/src/background/AppMediator.test.ts, projects/smoldot-browser-demo/src/index.ts
=> rename detect class to detector

CONTRIBUTING.md
Add a guide explaining how to make a good pull request that can be reviewed and merged quickly with some tips on testing and writing descriptions.
=> Add contributing guidelines for the project

.gitignore, projects/smoldot-browser-demo/.gitignore, projects/smoldot-browser-demo/package.json, projects/smoldot-browser-demo/src/view.ts, yarn.lock
=> Smoldot Browser Demo - Upgrade parcel to v2

projects/extension/src/components/Tab.tsx
ui for #234 
It's just a small button and adjusted paddings here. I couldn't think about >1 state for this, but let me know if I missed something!
=> component ButtonDisableTab

packages/smoldot-test-utils/package.json, projects/burnr/src/Home.tsx, projects/burnr/src/components/BalanceValue.tsx, projects/burnr/src/components/HistoryTable.tsx, projects/burnr/src/components/HistoryTableRow.tsx, projects/burnr/src/components/InputFunds.tsx, projects/burnr/src/components/SendFundsForm.tsx, projects/burnr/src/utils/constants.ts
=> Decimal sign can be added to transfer input

package.json
=> Fix Instructions concerning extension

yarn.lock
Creating this PR to merge the issues #269 #270  - as the CI was failing when opened from Github (just making sure)
=> Check if security issues pass CI

projects/extension/src/utils/debug.test.ts, projects/extension/src/utils/utils.test.ts
In order to increase coverage and have a start point for future utils that may be introduced (plus the fact that these tests were added in different PR that was solving another issue - thus they were ready), I add them as separate PR here
=> Add tests for debug.ts and utils.ts

projects/extension/src/background/SmoldotMediator.test.ts, projects/extension/src/background/SmoldotMediator.ts
Add SmoldotMediator.test.ts file that covers the unit tests of SmoldotMediator
=> Add SmoldotMediator tests

packages/connect/package.json, projects/burnr/package.json, projects/multiple-network-demo/package.json, projects/smoldot-browser-demo/package.json
Update substrate-connect version for it and projects to 0.3.7
=> Bump substrate-connect version to 0.3.7 (using smoldot 0.2.4)

projects/landing-page/src/App.tsx
=> Remove playground from sidebar

projects/extension/src/background/ConnectionManager.test.ts
Improve the unit test coverage for extension's ConnectionManager class.
=> ConnectionManager class - unit tests

projects/burnr/src/App.tsx, projects/burnr/src/components/NodeSelector.tsx
=> Burnr wallet: Fix various await errors (api.isReady)

projects/landing-page/src/components/Cards.tsx
=> Landing page - Reduce margin right to avoid new line on polkadot network 

projects/burnr/src/components/SendFundsForm.tsx
=> Fix wrap issue of transfer message;

projects/landing-page/src/App.tsx
=> Add banner in landing page mentioning that the project is experimental

projects/landing-page/src/App.tsx
=> Fix landing-page footer links

packages/connect/src/Detector.ts, projects/extension/src/background/AppMediator.ts, projects/extension/src/background/SmoldotMediator.ts
This PR adds documentation for all the core parts that were missing them.  This fixes #221
=> Add missing documentation

packages/connect/package.json, packages/smoldot-test-utils/package.json, projects/extension/package.json, yarn.lock
No bump of @substrate/connect yet.  Will bump and publish with the new generated docs in my next PR
=> Upgrade smoldot to 0.29.0

projects/landing-page/src/components/Logo.tsx, projects/landing-page/src/components/Sidebar.tsx, projects/landing-page/src/components/UIContainer.tsx
fixes #370. Might be a bit lazy, but I think it's ok for a temporary site
=> no menu down the md size screen

projects/burnr/src/App.tsx, projects/burnr/src/Home.tsx, projects/burnr/src/hooks/api/useLocalStorage.ts, projects/burnr/src/utils/utils.ts
A new function is added and runs 1 time at the initiation of the app, checks the existing localStorage keys and values and ensure that everything exist (if not it creates it with the default value) and if it exist but has no expected value it corrects it with the default one;
Fixes #375
=> Localstorage evaluation

projects/burnr/src/components/NavFooter.tsx
=> Add footer links in burnr wallet

projects/extension/src/background/index.ts
=> Fix extension - reconnection issue  existed when browser was restarted;

deploy.sh
=> Reactivate zip packaging and upload with deploy script

projects/landing-page/src/App.tsx
=> Hide the extension download from landing page and redirect Learn more to extension github

projects/extension/src/background/ConnectionManager.test.ts, projects/extension/src/background/ConnectionManager.ts, projects/extension/src/types/index.ts
Merge the entities of networks and chains into one
=> Extension - merge chains with networks

package.json, projects/burnr/package.json, projects/burnr/public/index.html, projects/landing-page/package.json, projects/landing-page/public/index.html, projects/multiple-network-demo/index.html, projects/multiple-network-demo/package.json, projects/smoldot-browser-demo/index.html, projects/smoldot-browser-demo/package.json, yarn.lock
- Parcel complains when "main" in the package.json is not a js file
- Parcel complains when using "import" but the entrypoint script tag
does not have type="module"
=> Upgrade parcel to 2.0.0-rc.0 and fix issues

projects/extension/src/components/Inputs.tsx, projects/extension/src/components/Tab.tsx, projects/extension/src/components/theme.tsx, projects/extension/src/containers/Popup.tsx
=> Extension UI Popup

projects/extension/src/containers/Options.tsx, projects/extension/src/containers/Popup.tsx
=> Add tabs in options

packages/connect-extension-protocol/src/index.ts
Added some introductory notes on the protocol as documentation to make understanding the types easier.
=> Improve protocol documentation

projects/extension/jest.config.ts, projects/extension/src/background/AppMediator.test.ts, projects/extension/src/background/AppMediator.ts, projects/extension/src/background/ConnectionManager.ts, projects/extension/src/background/types.ts, projects/extension/src/mocks.ts
Merge #458 first .. this PR builds on top
=> Allow the same app to connect in multiple tabs

projects/extension/src/components/NetworkTab.tsx
Add missing dependency on NetworkTab (extension)
=> Missing Dependency

packages/connect-extension-protocol/src/index.ts, packages/connect/src/ExtensionProvider/ExtensionProvider.ts
This field is useless and shouldn't be there in the first place.
=> Remove subscription field from MessageToManager

packages/connect/README.md
Remove a stray `()` on chainspec
=> minor fix on Readme

packages/connect/package.json, yarn.lock
Bump PolkadotJS and rpc-provider to v 5.8.3
=> Upgrade polkadotJS to 5.8.3

projects/extension/src/background/ConnectionManager.ts
https://github.com/paritytech/substrate-connect/pull/475
My bad
=> Fix bad documentation

packages/connect/src/Detector.test.ts, packages/connect/src/ExtensionProvider/ExtensionProvider.ts, packages/connect/src/SmoldotProvider/SmoldotProvider.ts, projects/extension/src/background/ConnectionManager.test.ts, projects/extension/src/background/ConnectionManager.ts, projects/extension/src/background/types.ts, projects/extension/src/components/NetworkTab.tsx, projects/extension/src/containers/Options.tsx, projects/extension/src/containers/Popup.tsx, projects/extension/src/types/index.ts, projects/extension/src/utils/utils.ts
Fixes #451 
Outcome of extension Options's page can be seen at the screenshot below:
=> Extension cleanup and improvements

projects/extension/src/components/NetworkTab.tsx
Alter Option page in order to fit Figma latest changes:
=> Fix options page of extension to be aligned with Figma

packages/connect/src/Detector.ts, packages/connect/src/SmoldotProvider/SmoldotProvider.test.ts, packages/connect/src/SmoldotProvider/SmoldotProvider.ts
SmoldotProvider implementation to support parachahins
=> Smoldotprovider supports parachains

packages/connect/package.json, packages/smoldot-test-utils/package.json, projects/extension/package.json
- Upgrade @substrate/smoldot-light to 0.4.18
- Bump substrate-connect to 0.4.4
- Bump extension to 0.0.3
=> Bump versions

projects/landing-page/src/App.tsx
Add a link for downloading latest extension from landing page - preparation for sub0
=> Add download link for browser extension

packages/connect/package.json, packages/connect/src/SmoldotProvider/SmoldotProvider.test.ts, packages/connect/src/SmoldotProvider/SmoldotProvider.ts, packages/smoldot-test-utils/package.json, packages/smoldot-test-utils/src/index.ts, projects/extension/package.json, projects/extension/src/background/ConnectionManager.ts, projects/extension/src/background/types.ts, projects/extension/src/mocks.ts, projects/extension/src/types/index.ts, yarn.lock
Rename JS types based on Smoldot PR [#1317](https://github.com/paritytech/smoldot/issues/1317)
Fixes #539
=> Rename Smoldot JS types

projects/burnr/src/components/InputAddress.tsx, projects/burnr/src/components/InputFunds.tsx, projects/burnr/src/components/SendFundsForm.tsx, projects/burnr/src/hooks/api/useApi.ts
=> Make the Fees calculation UI smoother

projects/landing-page/src/App.tsx, yarn.lock
Update landing page to include links for extension for both chrome and firefox stores
=> Update landing page with store's links

projects/extension/src/components/NetworkTab.tsx, projects/extension/src/components/Tab.tsx
Remove the App name from Options and Popup pages.
=> remove app names from UI

.github/workflows/yarn.CI.yml
- Update version 16.6.1 to 16.x; 
- Add version 17.x
=> Update node versions on CI

projects/extension/src/background/ConnectionManager.test.ts, projects/extension/src/background/ConnectionManager.ts
I can't believe that I missed this... :grimacing:
=> ConnectionManager: ensure that chain gets removed if port closes too early

projects/extension/src/background/ConnectionManager.ts, projects/extension/src/background/index.ts, projects/extension/src/containers/Options.tsx
This will keep the setting of notification to local browser only.
=> Replace chrome sync storage to local

packages/connect-extension-protocol/src/index.ts, packages/connect/src/ScProvider.ts, projects/extension/src/content/index.ts
Instead of copy-pasting this value, put it in `connect-extension-protocol`
=> Add DOM_ELEMENT_ID to protocol

packages/connect/src/createScClient/ScProvider/index.ts, packages/connect/src/createScClient/index.ts, projects/extension/src/background/ConnectionManager.ts, projects/extension/src/background/types.ts
Prepare for smoldot 0.6.1 update
=> Fix erroneous imports 

packages/connect/src/createScClient/ScProvider/Health.ts
Better fix than https://github.com/paritytech/substrate-connect/pull/783
=> Clean up health checker

.github/workflows/poc-zombienet.yml
Hi @wirednkod, this version has the `timeout` reporting fix we talk last week.
Thanks!
=> bump zombienet version

package.json, yarn.lock
- Addresses "node-forge" security vulnerabilities
=> Upgrade webpack-dev-server (security)

packages/connect/tsconfig.json
=> Exclude json specs from build

projects/demo/package.json, projects/extension/src/containers/Options.tsx, projects/extension/tsconfig.json
Adjust design of logs based on [Pierre's comment](https://github.com/paritytech/substrate-connect/issues/429#issuecomment-1098769324)
=> Fix extension log design

packages/connect/CHANGELOG.md, packages/connect/src/connector/smoldot-light.ts
Close https://github.com/paritytech/substrate-connect/pull/969
cc https://github.com/paritytech/substrate-connect/issues/965
This PR can be reviewed commit by commit.
=> Allow setting maxLoglevel when using the inline client

projects/landing-page/src/App.tsx
=> Update landing page examples

projects/extension/public/options.html, projects/extension/src/background/ConnectionManagerWithHealth.ts, projects/extension/src/background/index.ts, projects/extension/src/background/types.ts, projects/extension/src/components/Accordion.tsx, projects/extension/src/components/ConnectedTab.tsx, projects/extension/src/components/IconWeb3.tsx, projects/extension/src/components/NetworkTab.tsx, projects/extension/src/containers/Options.tsx, projects/extension/src/containers/Popup.tsx, projects/extension/src/main.css, projects/extension/src/types/index.ts, projects/landing-page/src/components/IconWeb3.tsx
The main purpose of this pr is to adjust to new figma by @Goranch3 - again #980)
This PR partially satisfies the bug list on #1074 
Rest of bugs will be corrected in a different PR.
=> Alter Options page based on Figma

projects/extension/src/components/NetworkTab.tsx
"Last" implies that there won't be any other block afterwards
=> Last block -> Latest block

deploy.sh
=> Apply name and email in deploy script

packages/connect/CHANGELOG.md, packages/connect/package.json, projects/extension/CHANGELOG.md, projects/extension/package.json, yarn.lock
=> Bump smoldot light to 0.6.27; 

package.json, packages/connect/CHANGELOG.md, packages/connect/package.json, yarn.lock
Since @wirednkod is on vacation, I'm insta-merging as insubstantial.
=> Publish NPM package v0.7.10

projects/extension/src/containers/Popup.tsx
=> Fix missing dependency on React Hook

.github/workflows/zombienet.yml
Rename zombienet poc to zombienet;
Bump zombienet and polkadot downad versions to latest;
=> Bump zombienet

projects/extension/CHANGELOG.md, projects/extension/public/manifest.json, projects/extension/src/background/index.ts, projects/extension/src/background/protocol.ts, projects/extension/src/containers/Options.tsx, projects/extension/src/containers/Popup.tsx, projects/extension/src/content/ClientWithExtension.ts, projects/extension/src/content/ExtensionMessageHandler.ts, projects/extension/src/content/index.ts, projects/extension/src/environment.ts
Close https://github.com/paritytech/substrate-connect/issues/1278
=> Final update to manifest v3

package.json, packages/connect/CHANGELOG.md, packages/connect/package.json, yarn.lock
=> Update checkpoints and bump SC to 0.7.19

projects/extension/CHANGELOG.md, projects/extension/package.json, projects/extension/public/manifest.json, projects/extension/src/background/index.ts, projects/extension/src/content/ClientWithExtension.ts, projects/extension/src/mocks.ts, projects/extension/webpack.config.js, yarn.lock
Bump Extension to 0.2.3
Replace @substrate/smoldot-light with smoldot 1.0.0;
=> Bump Extension to 0.2.3

packages/connect/src/connector/specs/rococo_v2_2.json
A follow-up PR to https://github.com/paritytech/substrate-connect/pull/1413
=> Switch Rococo bootnodes from WS to WSS

package.json, packages/connect/CHANGELOG.md, packages/connect/package.json, projects/extension/CHANGELOG.md, projects/extension/package.json, projects/extension/public/manifest.json, projects/extension/webpack.config.js, yarn.lock
- Bump smoldot to 1.0.2
- Bump substrate connect to 0.7.24
- Bump extension to 0.2.5
=> Bump smoldot to 1.0.2 and substrate connect

.gitignore, .prettierignore, packages/connect/build-js-specs.mjs, packages/connect/package.json, packages/connect/src/connector/specs/index.ts
=> fix: avoid importing json files

packages/connect/src/connector/smoldot-light.test.ts
It seems like the only issue that exists with `ViteTest` is the dynamic import which is not fully supported;
As a result I altered the code in order to revert to async await and use only `.then({})` syntax for the dynamic import where needed.
=> Revert async/await for vitest

.github/workflows/update-chain-specs.yml
Addresses bullet (b) from issue: https://github.com/paritytech/internal_it/issues/229
=> Alter ci chainspec user

.github/workflows/publish.yml
Fix deploy condition following [JS-DevTools migration guide](https://github.com/JS-DevTools/npm-publish#v2-migration-guide)
=> fix: deploy condition

projects/extension/src/components/Bootnodes.tsx, projects/extension/src/environment.ts
Fixes a race condition on bootnode initialization
=> fix: options page bootnodes

examples/light-client-extension-helpers-dapp/package.json, examples/light-client-extension-helpers-dapp/src/hooks/useChain.ts, examples/light-client-extension-helpers-extension/package.json, packages/light-client-extension-helpers/package.json, pnpm-lock.yaml, projects/demo/package.json, projects/demo/src/index.ts, projects/extension/package.json, projects/extension/src/hooks/useActiveChains.ts, zombienet-tests/package.json
- use `finalizedHeader$` observable
- use `bestBlocks$` observable
=> feat: update examples with the latest @polkadot-api

README.md
closes https://github.com/paritytech/substrate-connect/issues/1811
=> chore: update readme smoldot link

package.json, packages/connect-known-chains/package.json, packages/connect/CHANGELOG.md, packages/connect/package.json, packages/light-client-extension-helpers/package.json, pnpm-lock.yaml
Bump @substrate/connect (0.8.7)
Bump @substrate/light-client-extension-helpers (0.0.3)
Bump @substrate/connect-known-chains (1.0.7)
=> Bump Substrate connect (0.8.7)

examples/light-client-extension-helpers-dapp/src/App.tsx, examples/light-client-extension-helpers-extension/tests/dapp.spec.ts
=> fix(lc-ext-helpers-ext): increase playright test timeout

projects/wallet-template/src/background/createBackgroundRpc.ts, projects/wallet-template/src/containers/WalletPopup.tsx, projects/wallet-template/src/containers/WalletPopup/components/DecodedCallData.tsx, projects/wallet-template/src/containers/WalletPopup/hooks/useDecodedCallData.ts, projects/wallet-template/src/hooks/useActiveChains.ts
Add a React component that decodes call data
#1894
=> feat: add DecodedCallData component

packages/connect/package.json, pnpm-lock.yaml
Upgrade to @polkadot-api v0.0.1-492c132563ea6b40ae1fc5470dec4cd18768d182.1.0
=> chore(connect): upgrade @polkadot-api

projects/wallet-template/src/background/createBackgroundRpc.ts, projects/wallet-template/src/containers/WalletPopup.tsx
- parse sign request id from url
- remove sign request on popup close or DApp reload
=> feat(wallet-template): improve sign request handling

packages/connect-known-chains/package.json
=> release(connect-known-chains): 1.1.0

pnpm-lock.yaml, projects/wallet-template/package.json, projects/wallet-template/src/background/createBackgroundRpc.ts, projects/wallet-template/src/background/types.ts, projects/wallet-template/src/containers/WalletPopup.tsx, projects/wallet-template/src/containers/WalletPopup/components/ProtectedRoute.tsx, projects/wallet-template/src/containers/WalletPopup/components/index.ts, projects/wallet-template/src/containers/WalletPopup/hooks/index.ts, projects/wallet-template/src/containers/WalletPopup/hooks/useKeyring.tsx, projects/wallet-template/src/containers/WalletPopup/pages/ChangePassword.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Debug.tsx, projects/wallet-template/src/containers/WalletPopup/pages/LockKeyring.tsx, projects/wallet-template/src/containers/WalletPopup/pages/SignRequest.tsx, projects/wallet-template/src/containers/WalletPopup/pages/UnlockKeyring.tsx, projects/wallet-template/src/containers/WalletPopup/pages/index.ts, projects/wallet-template/src/wallet-popup.tsx
closes #1942 #1837
- add unlock keyring screen
- add change password screen
=> feat: add wallet password UI screens

projects/wallet-template/src/background/createBackgroundRpc.ts, projects/wallet-template/src/background/index.ts, projects/wallet-template/src/background/keyring.ts, projects/wallet-template/src/background/keystore/index.ts, projects/wallet-template/src/background/keystore/types.ts, projects/wallet-template/src/background/storage.ts, projects/wallet-template/src/background/types.ts, projects/wallet-template/src/background/utils.ts, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/Accounts.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/AddAccount/index.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/SwitchAccount.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/fetch.ts
- encrypt keyset secrets
- getAccounts uses keyset meta to return accounts
- signing is done using a keyset account keypair
=> feat: encrypt keyring secrets

projects/wallet-template/src/containers/WalletPopup/pages/Accounts/Accounts.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/AddAccount/index.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/SwitchAccount.tsx
Removes the shadows on the account pages
=> chore(wallet-template): accounts styling

.github/workflows/update-chain-specs.yml
- fix the commit title
- adds automerge label
=> chore: update chain-specs-periodic-update workflow

packages/connect-known-chains/package.json, packages/connect/CHANGELOG.md, packages/connect/package.json, packages/light-client-extension-helpers/package.json
Release and test new npm token
=> chore: release @substrate/connect 0.8.10

projects/wallet-template/assets/options.html, projects/wallet-template/src/containers/Options.tsx, projects/wallet-template/src/containers/WalletPopup.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/Accounts.tsx
- fix the duplicate chainspec tab
- fix the route from `/accounts/options` -> `/options`
=> fix(wallet-template): options page

projects/wallet-template/src/style.css
Tweak the CSS colors for the wallet template. Used in #2196, #2194
=> chore(wallet-template): update styling colours

projects/wallet-template/src/containers/WalletPopup/pages/Accounts/ImportAccounts.tsx
=> chore: update import page

packages/unstable-wallet-provider/UnstableWalletProviderDiscovery.d.ts, pnpm-lock.yaml, projects/wallet-template/src/inpage/index.ts, projects/wallet-template/src/inpage/pjsInject.ts
Removes the `Promise` around provider and wraps the wallet template inpage in an async call.
See the discussion here for more details: https://github.com/paritytech/substrate-connect/pull/2200#discussion_r1619140897
=> chore(wallet-template): remove provider promise

projects/wallet-template/src/containers/WalletPopup/pages/ChangePassword.tsx
=> chore(wallet-template): update confirm password

projects/wallet-template/src/containers/WalletPopup/pages/Accounts/AccountDetails.tsx
=> chore(wallet-template): update account details page

projects/wallet-template/src/background/index.ts, projects/wallet-template/src/containers/WalletPopup/pages/AddChainByUser.tsx
=> chore(wallet-template): update add chain by user popup

packages/connect/CHANGELOG.md
TODO: make sure @substrate/discovery packages are also published to pnpm which they are not...
=> fix(connect): add missing 1.0.0 changelog

packages/light-client-extension-helpers/src/background/background-helper.ts
#1786 
Optimstically tries to fix an issue where a chain gets "stuck in the past" for some arbitary reason thats not related to smoldot crashing by recreating the json-rpc-provider/substrate-client/observable-client whenever there is an error in follow chains.
- `pnpm turbo build` in the root repo
- Load the extension and demo app.
- Watch the extension console for craziness and make sure the blocks keep moving...
=> fix: chains getting stuck

examples/light-client-extension-helpers-extension/package.json, packages/connect/package.json, pnpm-lock.yaml, projects/extension/package.json, projects/wallet-template/package.json
Updates smoldot to include a fix where chains were getting stuck.
https://github.com/smol-dot/smoldot/issues/1873
=> chore: update smoldot to 2.0.29

.github/workflows/ci.yml, packages/connect/CHANGELOG.md, packages/connect/package.json, packages/light-client-extension-helpers/package.json, projects/wallet-template/src/background/index.ts, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/AddAccount.tsx, projects/wallet-template/tests/demo.spec.ts, projects/wallet-template/tests/fixtures.ts
Update playwright tests for wallet template.
https://www.loom.com/share/56300629ff0744ba89ba9a281fa06105?sid=3bbd8b72-3e28-45e5-8192-5791dfe828ac
=> chore(wallet-template): update playwright tests

pnpm-lock.yaml, projects/wallet-template/package.json, projects/wallet-template/playwright.config.ts, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/AccountDetails.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/Accounts.tsx, projects/wallet-template/src/containers/WalletPopup/pages/Accounts/ImportAccounts.tsx, projects/wallet-template/src/containers/WalletPopup/pages/ChangePassword.tsx, projects/wallet-template/tests/demo.spec.ts, projects/wallet-template/tests/utils.ts, projects/wallet-template/tests/wallet.spec.ts
https://www.loom.com/share/efb4f6494e6d427d8c395384edcb72a1?sid=75d42b8c-8874-44d5-aeb6-6fd6e77ac3ff
Add playwright tests to the wallet template for:
- Password/Password Reset/Lock Screen
- Add Account
- Import Mneonic
- Import Private Key
=> chore(wallet-template): add more playwright tests

.changeset/plenty-taxis-wait.md, README.md, packages/connect-discovery/README.md, packages/connect-known-chains/README.md, packages/connect/README.md, packages/connect/src/connector/index.ts, packages/discovery/README.md, packages/smoldot-discovery/README.md
addresses the feedback in: https://github.com/paritytech/substrate-connect/pull/2374
=> chore: improve docs

.changeset/serious-hornets-approve.md, .changeset/silly-files-exercise.md, packages/connect-known-chains/package.json, packages/connect-known-chains/specs/polkadot_people.json, packages/connect-known-chains/specs/westend_people.json
closes: #2387 
The state root hash for `westend-people` is wrong but after this is merge the bot will update it.
=> chore: add people chainspecs

.github/workflows/update-chain-specs.yml
=> chore: update "chainspecs workflow" to use new authorized github app token

.github/workflows/ci.yml, .github/workflows/pr-ci.yml, .github/workflows/reusable-ci.yml
closes: https://github.com/paritytech/security/issues/86
prevents getting pwned: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
=> fix: security issues with CI

.github/workflows/dependabot-changeset.yml
https://github.com/mscharley/dependency-changesets-action/issues/329
=> fix: dependabot changeset ci action

.changeset/twelve-bananas-sin.md, packages/connect-known-chains/package.json, packages/connect-known-chains/specs/ksmcc3_people.json, packages/connect-known-chains/src/index.ts
- Adds Kusama People
- Fixes Missing Westend People and Polkadot People exports
=> feat: update people parachain specs

packages/light-client-extension-helpers/src/tx-helper/polkadot-api/tx-helper/tx.ts, packages/light-client-extension-helpers/src/tx-helper/polkadot-api/tx-helper/types.ts
fix some minor issues in comments
=> chore: fix some minor issues in comments
