- packages/smoldot-provider/src/BrowserDatabase.ts
- packages/smoldot-provider/src/Database.ts
- packages/smoldot-provider/src/FsDatabase.test.ts
- packages/smoldot-provider/src/FsDatabase.ts
- packages/smoldot-provider/src/SmoldotProvider.test.ts
- packages/smoldot-provider/src/SmoldotProvider.ts
- packages/smoldot-provider/types/smoldot/index.d.ts
This adds functionality to check if an existing database exists (either saved to disk in node or in the local storage in the browser) and provides it to the smoldot client when `connect` is called on the `SmoldotProvider`.  There are no user facing changes, it should just now do the right thing.
> Check for existing state and pass it to the smoldot client

- packages/smoldot-provider/package.json
- packages/smoldot-provider/src/SmoldotProvider.test.ts
- packages/smoldot-provider/src/SmoldotProvider.ts
- packages/smoldot-provider/src/errors.ts
This is the implementation of lifecycle events outlined in #60.  I have deviated from the initially planned implementation.
After extensive testing against Westend and  comparing with the `WSProvider`, I discovered that the length of time to get peers is highly variable.  It can be almost instant but it can take over 10 seconds.  The client is still usable with no peers but it will not respond to certain queries.  Therefore it doesn't makes sense to simulate the "error if we don't connect behaviour" unless we get errors from the `system_health` request. 
Also after discussing with Gav and Pierre on element, there is another property on the health response that is relevant: `shouldHavePeers`. This is set to `false` for development chains which are not expected to have any peers and the …
> Improve SmoldotProvider event emitting

- projects/smoldot-extension/src/assets/manifest.json
> Fixed manifest warning in FF extension

- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/SmoldotMediator.ts
- projects/extension/src/background/mocks.ts
- projects/extension/src/background/types.ts
* Tests for the message multiplexing - both regular messages and subscriptions.
* Fixes the messages being send to all apps regardless of the smoldot they came from by registering the app with a particular smoldot
* Expects to be told when a message is a subscription in the message posted through the port.  This means when the `subscription` parameter in the `send()` function on the provider is passed you must add a `subscription: true` property to the message you post send through the port.
> Rm test extension background

- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/SmoldotMediator.ts
- projects/extension/src/background/mocks.ts
- projects/extension/src/background/types.ts
When the port for a UApp disconnects we put its `AppMediator` into the `disconnecting` state and send an unsubscribe message for all the active susbcriptions.  There is an additional check in the smoldot message processing to see if we're disconnecting and to change the state to `disconnected` once all those unsubscribe messages have been responded to by the smoldot.
The test for disconnecting adds some subscriptions; calls disconnect; simulates the unsub repsonses and checks the state of the UApp at all stages.
I also refactored the unit tests to make them more readable and reusable and to add better assertion coverage of all the behaviours.
* Handling unsubscribe messages from the UApp - I need to coordinate with you after we've merged this and your work to get the `ExtensionProvider` …
> Unsubscribe from all subscriptions when a UApp disconnects

- packages/connect/.eslintignore
- packages/connect/package.json
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- packages/connect/src/SmoldotProvider/BrowserDatabase.ts
- packages/connect/src/SmoldotProvider/FsDatabase.ts
- packages/connect/src/SmoldotProvider/SmoldotProvider.ts
- packages/connect/src/SmoldotProvider/errors.ts
- packages/smoldot-provider/tsconfig.tsbuildinfo
This enables linting for @substrate/connect  I have removed the `params` from the subscription state in both providers.  This was copy/pasted over from the `WsProvider` where it keeps track of that so that it can resubscribe to any subscriptions if the websocket connection drops.  This doesn't make sense for our providers as we shouldn't have this connectivity loss problem
> Lint connect package

- .editorconfig
Does what it says on the tin.  Enforces:
* 2 spaces for tabs (company policy)
* UTF-8 (common sense)
* Trailing new line in files [to avoid "No newline at end of file" warnings in git diffs](https://thoughtbot.com/blog/no-newline-at-end-of-file) *TIL: this isn't the default in vscode ... why?!* :confounded:
* Unix line endings (none of us use windows)
> Add editorconfig to enforce whitespace rules

- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/.eslintignore
- projects/extension/jest-setup.js
- projects/extension/jest.config.ts
- projects/extension/package.json
- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/content.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- projects/extension/src/content/index.ts
- projects/extension/src/mocks.ts
- projects/extension/src/types/index.ts
- projects/extension/webpack.config.js
- yarn.lock
This implements disconnect in the extension provider (fixes #168) which will now send a message to the content script telling it to disconnect the port to the background and emits the `disconnected` event on the provider.
I took the opportunity to add a full suite of tests for the content script message routing behaviours.  I had to refactor the routing out to make it easier to test.
> Implement disconnect on ExtensionProvider and test content script message routing

- packages/connect/package.json
- projects/burnr/package.json
- projects/extension/src/content/ExtensionMessageRouter.ts
- projects/multiple-network-demo/package.json
- projects/smoldot-browser-demo/package.json
- yarn.lock
I have made the warnings more explicit.  Added a specific warning for the case where there is no `action` and standardised the formatting.  
I also bumped the @substrate/connect version with a minor version number change as it affects the API between @substate/connect and the demos. (Although [the version numbers don't mean anything](https://semver.org/#spec-item-4) for a major version of "0")
> Fix extension provider malformed message warnings and bump @substrate/connect version

- packages/connect/package.json
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- packages/connect/src/ExtensionProvider/types.ts
- packages/connect/src/SmoldotProvider/SmoldotProvider.ts
- projects/burnr/package.json
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- projects/multiple-network-demo/package.json
- projects/smoldot-browser-demo/package.json
This fixes #228.  In the `ExtensionMessageRouter` when we received a message through the port from the background we were only sending its `payload` via `window.postMessage` on to the app.  The background could send either an `rpc` message where the payload was a JSON string or an `error` where the payload would be an error message.  I adjusted the `ExtensionMessageRouter` to send the whole message and not just the `payload`.  I also adjusted the `ExtensionProvider` to check for `error` message types and emit an error event instead of trying to process it as if it was an RPC message.
> Handle errors sent from the extension background to the app properly

- packages/connect-extension-protocol/package.json
- packages/connect/package.json
- projects/extension/package.json
Regardless of wether we do #242 I think it is preferable not to commit to v1.0.0 before we are ready to launch publicly.  You never know we may discover the need to make breaking changes between then and now.
> Change connect-extension-protocol version to v0.1.0

- packages/connect-extension-protocol/package.json
- packages/connect-extension-protocol/src/index.ts
- packages/connect/package.json
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/burnr/package.json
- projects/extension/package.json
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- projects/multiple-network-demo/package.json
- projects/smoldot-browser-demo/package.json
This fixes #234 - The UI can now specifiy a tab and have all the connections from that tab gracefully disconnected.  All the ports will be closed, all active subscriptions will be unsubscribed and the content script will notify the `ExtensionProvider` in the app that the connection was closed so that it can raise its disconnect event for the UApp to handle as it sees fit.
```javascript
manager.disconnectTab(42);
```
> Implement disconnectTab to gracefully disconnect all connections from a tab

- packages/connect-extension-protocol/package.json
- packages/connect-extension-protocol/src/index.ts
- packages/connect/package.json
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/burnr/package.json
- projects/extension/package.json
- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/types.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- projects/extension/src/types/index.ts
- projects/landing-page/src/App.tsx
- projects/multiple-network-demo/package.json
- projects/smoldot-browser-demo/package.json
This fixes #242 - significantly simplifying the message parsing and handling on the extension side.
When a user has the extension installed and an app connects the `ExtensionProvider` now sends a message with the type `connect` instead of an `associate` message.  The `ExtensionMessageRouter` in turn connects to the background as before but no longer sends an `associate` message.  The `AppMediator` parses the network name out of the port name and becomes `connected`. 
If the background does not have a client for the network named it sends an error back to the app (as before) and disconnects the app.  If the port name is in the wrong format the background also sends an error back (this shouldn't ever happen as we control the content script).
There is no need for a separate `ready` state as …
> Remove associate message and ready state

- packages/connect/package.json
- packages/connect/src/SmoldotProvider/SmoldotProvider.test.ts
- packages/smoldot-test-utils/package.json
- packages/smoldot-test-utils/src/index.ts
For this pull request I've only achieved some of what I'd hoped but the key change here is that you are now able to specify a sequence of health responses when testing your new 'connected' behaviour (previously you could only control the 'hasPeers' property of the health responses).
In the process I also reorganised and documented all of smoldot-test-utils and refactored some things to make them more readable.  I also enabled linting and fixed all the problems.  
You might find it easier to review this pull request by reviewing each commit one-by-one instead of viewing the "Files Changed" for the whole PR. I was careful to do each refactoring in a small step and to commit after (although I did retrospectively fix a couple of errors I'd missed as I went).  
My vision with …
> Make mocking system_health more flexible

- projects/landing-page/src/App.tsx
This fixes the examples and links in the landing page.  It also updates the status of the networks to indicate support of kusama and polkadot and changing rococco to "soon". I also removed the playground text from the footer as it doesn't currently make any sense.  I looked at it in both Firefox and Chrome but you probably want to have a look yourself @goldsteinsveta as there is now quite a large black space where that text was before.
> Landing page fixes

- projects/burnr/src/components/NodeSelector.tsx
- projects/burnr/src/hooks/api/useApiCreate.ts
- projects/burnr/src/utils/constants.ts
- projects/burnr/src/utils/utils.ts
There was an issue with burnr wallet mainly due to the upgrade of polkadotJS api to latest version.
That was not allowing the wallet to initiate. In addition through previous PRs a bug was introduced that when localStorage was empty, there was no init of the app due to the fact that localStorage was never init'ed before.
Besides the issues/bugs mentioned above - after a short discussion with @goldsteinsveta it seemed like a good idea to remove the live networks from an application like burnr wallet in order to ensure that there will not be any loss of funds.
> Fix burnr wallet provider issues and deactivate Live clients

- .eslintrc.js
- packages/connect-extension-protocol/package.json
- packages/connect/package.json
- packages/connect/src/__mocks__/client.js
- packages/smoldot-test-utils/package.json
- projects/burnr/.eslintignore
- projects/burnr/.eslintrc.js
- projects/burnr/package.json
- projects/burnr/src/utils/constants.ts
- projects/extension/.eslintrc.cjs
- projects/extension/package.json
- projects/landing-page/.eslintignore
- projects/landing-page/.eslintrc.js
- projects/landing-page/package.json
- projects/multiple-network-demo/package.json
- projects/smoldot-browser-demo/package.json
This PR fixes #293.  I have moved all the common eslint configuration into a root `.eslintrc.js`.  I favoured using a separate js file since it is easier to read when its not embedded in a `package.json` and we can use comments to explain why we configured / disabled rules if we want to.  Many of the projects no longer have any eslint config but those that do now have a minimal `.eslintrc.js` file specifying only the project-specific overrides.  I also removed the `no-misused-promises` rule as there were no errors and I moved the `restrict-plus-operands` rule config to the root.
> Share eslint config across projects

- package.json
- packages/connect/.eslintignore
- packages/connect/.eslintrc.cjs
- packages/connect/src/Detector.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/tsconfig.eslint.json
- projects/extension/.eslintignore
- projects/extension/.eslintrc.cjs
- projects/extension/tsconfig.json
- projects/extension/webpack.config.js
This PR configures eslint with new options to force typescript-eslint to understand our project references and solve the problem of the types for `connect-extension-protocol` not being available when you try to lint the `connect` or `extension` projects before you have built.
Project references are [not officially supported yet](https://github.com/typescript-eslint/typescript-eslint/issues/2094) by typescript-eslint. Adding the paths to the tsconfigs for dependent projects into `parserOptions.project` is [*supposed* to be a workaround](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/parser#parseroptionsproject). Unfortunately it doesn't.
Someone from the community found [a way to make it work](https://github.com/typescript-eslint/typescript-eslint/issues/2094#is …
> Make eslint aware of dependent typescript projects

- packages/connect/package.json
- packages/smoldot-test-utils/package.json
- projects/extension/package.json
- yarn.lock
It is needed to match Smoldot to exactly 0.2.6 for now - due to the issue that exists with smoldot debug build that creates the Javascript heap memory error (v 0.2.7 and 0.2.8).
This PR removes the caret (^) as if it is there then upon substrate-connect install latest minor or patch version (e.g. 0.2.8). This affects the  `apps` build and thus the progress of the integration of apps with Substrate connect light client.
Note: _A new version should be published in NPM once this PR is merged._
> Bump smoldot to match exactly v 0.2.6

- packages/connect/package.json
- packages/smoldot-test-utils/package.json
- projects/extension/package.json
- projects/landing-page/package.json
- projects/multiple-network-demo/package.json
- projects/smoldot-browser-demo/package.json
- yarn.lock
As soon as 27 is officially released I thought its a good idea to bump the version to a stable (^27.0.5) one instead of (^27.0.0-next.9). Run deep clean and test and all passed.
> Bump jest version to stable 27.0.5 instead of @next

- deploy.sh
If you don't disable jekyll it breaks the pages that with start with an underscore (which we have in the API docs).  We aren't using jekyll anyway.  I also removed the unused jekyll build function in the deploy script.
This PR also forces the deployment to do a fresh production build before deploying.  Commonly we are testing the demos and landing page using `yarn dev` before deploying to check everything is ok.  Without this, it is easy to accidentally deploy a debug build of the apps / landing page to gh-pages.  The landing page will not work with a debug build on gh-pages.
> Disable jekyll in gh-pages and build before deploying

- projects/landing-page/src/App.tsx
Put API Documentation section (and menu) before Projects as it seems to make more sense this way
> Flip positions of API documentation and projects in landing page

- projects/burnr/src/components/BalanceValue.tsx
- projects/burnr/src/components/SendFundsForm.tsx
Following enhancements took place:
- Alter formatting of values (remove unit prefixes) to use base unit.
- Alter message during transaction from "Receiver will get" to "Balance after transaction"
Fixes #374
> Minor enhancements on Send Funds

- packages/connect/package.json
- packages/connect/src/SmoldotProvider/SmoldotProvider.test.ts
- packages/connect/src/SmoldotProvider/SmoldotProvider.ts
- packages/smoldot-test-utils/package.json
- packages/smoldot-test-utils/src/index.ts
- projects/extension/package.json
- projects/extension/src/background/SmoldotMediator.test.ts
- yarn.lock
- Bump version of smoldot to v3.1
- Update SmoldotProvider to new API; 
- Update smoldotTestUtilScripts;
(Tests fail on SmoldotMediator - for now opening a draft PR)
> Update SmoldotProvider and respective tests to support smoldot v3

- packages/connect/package.json
- packages/connect/src/Detector.ts
- projects/burnr/package.json
- projects/landing-page/src/App.tsx
- projects/multiple-network-demo/package.json
- projects/smoldot-browser-demo/package.json
This PR splits the .connect() function to 2. One provider() function that detects and returns the detected Provider (SmoldotProvider or ExtensionProvider) and a simplified connect() that is using the latter for the functionality that was already implementing.
Reason of this split is having the provider() function for advanced usage (e.g. PolkadotJS) and for internal use.
> Split detector to Connect and Provider functions

- packages/connect/extension-resolver.cjs
- packages/connect/jest.config.ts
- packages/connect/package.json
- packages/connect/src/Detector.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- packages/connect/src/ExtensionProvider/index.ts
- packages/connect/src/SmoldotProvider/SmoldotProvider.ts
- packages/connect/src/SmoldotProvider/index.ts
- projects/burnr/package.json
- projects/multiple-network-demo/package.json
- projects/smoldot-browser-demo/package.json
- yarn.lock
Added an extension-resolver for jest that does exactly what we are searching for: finding .js extensions and replacing them temporary with .ts for ts-jest to run.
> Fix issue with extensions .js that was breaking ts-jest

- packages/connect/tsconfig.json
In this PR I am adding the .parcel-cache and node_modules in exclusion of base tsconfig (connect package).
With the latest changes that took place, now all packages/projects, correctly includes the base tsconfig from connect package in order to have the reference of projects across.
The huge load of files (especially in .parcel and node_modules) though in each project, now makes the VSCode linter to break.
More specifically:
```
$. du -a | cut -d/ -f2 | sort | uniq -c | sort -nr
93997 node_modules <---
16582 .parcel-cache   <---
4660 .git
2010 projects
251 packages
13 coverage
```
As soon as these dirs are not App specifics they should be excluded in tsconfig.
> Exclude node modules and parcel cache from tsconfig

- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/index.ts
- projects/extension/src/background/types.ts
- projects/extension/src/mocks.ts
This fixes #438.  It also fixes 2 bugs in the implementation.
* The `AppMediator` was asking the `ConnectionManager` to send messages on its behalf but the `ConnectionManager` would just pick the first chain with the matching name instead of using the chain that was created for that `AppMediator`.  I removed the message sending from the `ConnectionManager` and the `AppMediator` just asks the chain it has to send the message.
* If an RPC message was received before a spec message or before `addChain` had completed then it would crash because the chain was not yet defined.  I now buffer any early RPC messages that come in and when the `addChain` completes check for those messages and send them all.
I spotted a couple more small issues with the implementation but they aren't causing complete …
> Extension Refactor - remove request and subscription tracking

- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- Test that disconnect is called after sending an error when an app
already exists
- Improve some of the test names
- Only show a notification to the user if an app successfully connects.  The app will get an error if it fails so it is the app's responsibility to update it's UI to tell the user.
This is the first part of #442. I'm splitting the PRs to make it easier to review instead of having several small unrelated changes mixed together.
> Improve ConnectionManager tests and fix notification behaviour

- projects/extension/jest.config.ts
- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/types.ts
- projects/extension/src/mocks.ts
- Don't catch the error when adding the chain - use the message to send
it back to the app.
- Add missing tests for sending an error when the port name is not valid
This closes #442
> Send the right error message when addChain fails and add missing tests for all error cases

- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- packages/connect/src/utils/index.ts
- packages/connect/src/utils/utils.test.ts
When the extension disconnects an app for an error the `ExtensionProvider` now rejects any pending req	uest promises.  This is a direct copy of the logic from the WsProvider
> Reject pending requests on disconnect

- packages/connect/package.json
- packages/connect/src/SmoldotProvider/SmoldotProvider.test.ts
- packages/connect/src/SmoldotProvider/SmoldotProvider.ts
- packages/smoldot-test-utils/package.json
- packages/smoldot-test-utils/src/index.ts
- projects/extension/package.json
- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/types.ts
- projects/extension/src/mocks.ts
- projects/extension/src/types/index.ts
- yarn.lock
- replacing deprecated smoldot package with @substrate/smoldot-light
- adds in `packages/smoldot-test-utils/src/index.ts` the mock for healthChecker
> Replace smoldot with @substrate/smoldot-light

- DEPLOY-RELEASE.md
- README.md
* Add a link to the gh-pages deployed landing page to top of README
* Update README first section so:
* its much shorter
* correct now we're using smoldot
* not marketing blurb (we will have blog posts and presentations for that)
* Add a link to the deployed API documentation from the README
* Add a link to the CONTRIBUTING guidelines from the README
* Move deployment instructions out of README into its own document
> Improve and update README

- packages/connect/package.json
- packages/smoldot-test-utils/package.json
- projects/extension/package.json
- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/types.ts
- projects/extension/src/mocks.ts
- yarn.lock
- Bump version of smoldot light to 0.4.4
- Add implementation of HealthChecked in Extension: Each Chain should have 1 HealthCheck. As a result the return of the addChain in ConnectionManager is a ChainInstance object that contains a) chain: the addedChain and b) healthChecker for the specific chain. This way the manipulation of the HealthChecker is passed in the AppMediator.
- Alter tests for healthCheck.
> Integrate HealthChecker in Extension

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/Detector.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/types.ts
- projects/extension/src/types/index.ts
This removes passing the `relayChainName` from the foreground to the extension. Which relay chain a parachain should connect to is already found in the chain specification, so there's no need to additionally pass the same value as a separate parameter.
I've noticed that the `connect` method of the detector is broken, but it's already broken before this PR and can be fixed afterwards.
> Remove sending the relay chain name to the extension

- projects/extension/src/background/AppMediator.test.ts
- projects/extension/src/background/AppMediator.ts
- projects/extension/src/background/ConnectionManager.ts
Instead of doing `const app = new AppMediator(...)` followed with `app.associate()`, this PR merges these two functions into one.
In other words, the constructor implicitly calls what used to be `associate()`, and throws if `associate()` fails.
> Remove AppMediator::associate

- projects/extension/src/background/AppMediator.ts
No longer pass the chain name to `handleSpecMessage` since it's stored in `this` anyway.
> Fix small stupidities regarding chainName in AppMediator

- projects/smoldot-browser-demo/package.json
- projects/smoldot-browser-demo/webpack.config.js
- yarn.lock
Convert smoldot browser demo to webpack in order for Demo to work without the need of extension
> Convert smoldot browser demo to webpack

- packages/connect/package.json
- packages/connect/src/Detector.ts
- packages/connect/src/specs/generate-specs.js
- packages/connect/src/specs/index.ts
I recently tested the performance of the loading times on a project that was using `substrate-connect` and the performance metrics were not looking good.
After some analysis, I was able to confirm that the main reasons were:
- Loading and parsing on the main JS chunk the JSON files for all the known chain-specs.
- Loading on the main JS chunk both providers (SmoldotProvider and ExtensionProvider)
- Loading on the main JS chunk `@polkadot/api`
Luckily for us, we can dynamically load the provider that the user needs when they call `connect`, while in a parallel request we load the `@polkadot/api`. That's what the first commit of this PR does.
However, what was penalizing the performance the most was the issue with the JSON files... I had to get a bit creative to solve that one. This is the …
> Improving loading times on substrate-connect

- projects/extension/src/background/ConnectionManager.test.ts
We've seen a [task inconsistently failing on a particular test](https://github.com/paritytech/substrate-connect/runs/4301859471), which seems to indicate that's a flaky test. This PR is an attempt to address that issue. Although, IMO using this `waitForMessageToBePosted` is far from ideal. However, this is the method used in all the other tests to "prevent" the race condition... So, for now that should do the trick. Although, it would be worth it to review these tests in the future and see if we can find a better way to handle these kinds of situations.
> test: fix flaky test on ConnectionManager

- packages/connect/src/ScProvider.ts
- projects/smoldot-browser-demo/src/index.ts
There have been a miss on this [PR](https://github.com/paritytech/substrate-connect/pull/554) that  is exposing the provider.
This has to do with the initiation of the light client.
At the moment, the provider is returned when the `new ScProvider(name, chain)` is called but there is no action that initiates the Smoldot Client. That initiation is taking place with `connect()`.
There are 2 approaches that we could follow to fix this:
a) Increase the lines of code from 2 to 3, from the dApp, in order to init the smoldot light client, meaning:
```javascript
const provider = new ScProvider("Smoldot Browser Demo", SupportedChains.westend,)
provider.connect()  // <--- added line
const api = await ApiPromise.create({ provider })
```  
b) call the `connect()` in the constructor of the ScProvider …
> Add connect() in ScProvider constructor

- packages/connect-extension-protocol/package.json
- packages/connect-extension-protocol/src/index.ts
- packages/connect/package.json
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/package.json
It addresses the first bullet point of #572
> Merge CommonProviderMessageData and ProviderMessageData into one interface. I suspect that the reason why they're two separate thing is to make the code in ExtensionProvider easier, but that's really not the problem of connection-extension-protocol
I also took that chance to remove the public properties `name` and `chainSpec` from the ExtensionProvider, since those properties shouldn't be exposed... I could (and perhaps should) do that in a separate PR, though.
> chore: merge CommonProviderMessageData and ProviderMessageData

- .github/workflows/yarn.CI.yml
https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install
Assuming it works correctly (you never know with JS), this make sure that any update to the `package.json` must come with its associated changes in `yarn.lock` in the same PR.
> Enforce frozen lockfile in CI

- bin/node-esm
- packages/connect/package.json
- projects/extension/package.json
Reasons to remove are:
- It's really not worth have a separate script just for passing two flags to `node`.
- There's fundamentally no reason why the `connect` package and the `extension` package would always use the same flags. There's no "DRY" argument for this script, because you _should_ repeat yourself here.
- It adds an indirection when reading the `package.json`. Instead of knowing what `npm test` does, you have to additionally open another file.
> Remove node_esm script from bin

- packages/connect/package.json
I don't really see why it's there?
The `>=14` seems completely arbitrary (do we use a feature that was added in Node 14?), and `<=16.13.0` seems completely arbitrary as well considering that `v16.13.1` and `v17` exist.
> Remove the "engines" requirement from package.json

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- Remove the `extension` and `provider` variables. It doesn't make sense to use the variable `provider` when in the extension and vice versa, so why are they available? Again, sending and listening is out of scope of the `connection-extension-protocol` package which should only provide the protocol.
> Remove extension and provider variables from connect-extension-protocol

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- Also remove the `ExtensionMessage` and `ProviderMessage` interfaces, again to simplify. The actual type that the callback passed to `addEventListener` receives is [`MessageEvent`](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent) (which as a field named `data`), and not `ExtensionMessage` or `ProviderMessage`. You can't actually know in advance what the `data` field contains in this context.
> remove `ExtensionMessage` and `ProviderMessage`

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- Remove the `ExtensionMessageData.disconnect` field, because it's exactly the same thing as `MessageFromManager.type` being equal to `error`.
> remove `ExtensionMessageData.disconnect`

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- packages/connect/src/ScProvider.ts
- projects/burnr/src/hooks/api/useApiCreate.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- projects/multiple-network-demo/src/index.ts
- projects/parachain-demo/src/index.ts
- projects/smoldot-browser-demo/src/index.ts
- Remove the `appName` field. Instead the extension should simply use the tab URL. We can always revisit later the decision of removing app names, but for now let's get rid of this field in order to unlock progress.
> remove `appName` field

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- Remove from the `ExtensionProvider` the code that was sending a message with the `connect` action. The extension can do what it was doing when receiving a `connect` event at initialization and/or the first time it receives an actual message.
> remove `connect` action from `ExtensionProvider`

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- Remove the `action` field, because all messages are automatically considered as `forward`. There's no need for the `connect` and `disconnect` messages. The code of `disconnect` can simply be removed for now. Update the content script of the extension to simply connect to the extension and forward messages back and forth. It doesn't have to do anything more.
> remove `action` field from `ExtensionProvider`

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- Remove the `chainName` field. Instead the extension should use the chain name found in the chain spec.
While I was working on splitting the message type `spec` into `add-chain`/`add-well-known-chain`, I realized that change was going to be a lot smaller and simpler if the `chainName` field had already been removed, so I decided to tackle this one first.
> remove `chainName` field from `ToExtension`

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- packages/connect/src/ScProvider.ts
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/index.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
-  `MessageToManager.type` equal to `spec` should instead be two different variants: `add-chain` or `add-well-known-chain`. Depending on which one, you pass either a chain spec or the id of a well known name ("rococo_1_3", "westend", "polkadot", or "ksmcc3").
> split `MessageToManager.type` into `add-chain` and `add-well-known-chain`

- projects/extension/public/manifest.json
At the moment Extension (on chrome) throws error:
`CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder`
This addition to the manifest will allow extension to run correctly on chrome.
In a following revision (manifest v3) this should be replaced with [sandboxed file](https://developer.chrome.com/docs/extensions/mv3/sandboxingEval/)
> Update CSP of extension to include unsafe-eval

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- The `chainId` field should be present in the `ToApplication` interface so that the listener can filter-out those messages that were not targeting its chain.
This also addresses the "routing" issue that's described in #550
> Add `chainId` into `ToApplication` interface

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- packages/connect/src/ExtensionProvider/getRandomChainId.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
> `chainId` counter -> random string

- packages/connect/package.json
- packages/smoldot-test-utils/package.json
- projects/extension/package.json
- yarn.lock
This makes us compatible with the "new" chain spec format where `codeSubstitutes` contains a block number (https://github.com/paritytech/substrate/pull/10600)
> Update smoldot to 0.5.13

- projects/extension/package.json
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/index.ts
- projects/extension/src/background/types.ts
- projects/extension/src/components/Tab.tsx
- projects/extension/src/containers/Options.tsx
- projects/extension/src/containers/Popup.tsx
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- projects/extension/src/mocks.ts
- projects/extension/src/types/index.ts
I feel bad for opening such a large PR. So, I would like to explain how and why it came to this.
When I started working on #571, the very first thing that I did was to define a new public interface that looked like this:
```ts
export interface ExposedChainConnection {
chainId: string;
chainName: string;
tabId: number;
url: string;
healthStatus?: SmoldotHealth;
}
export interface Background extends Window {
manager: {
onManagerStateChanged: (
listener: (state: ExposedChainConnection[]) => void
) => () => void;
disconnectTab: (tabId: number) => void;
};
}
```
Which is all what needs to be exposed so that the UI can display the state of the different connections.
Next, I updated the code in the React components to leverage this new API. So far, so good.
Up until this point, I hadn't even …
> refactor ConnectionManager

- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/types.ts
- The extension should be updated to use the `chainId`, accompanied with the `tabId`, to identify chains.
> use both `chainId` & `tabId` to identify chains

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/types.ts
- When you send a message to add a chain, the extension should return ~~two~~ one message~~s~~ that ~~don't~~ doesn't exist yet: ~~one "add-chain-started" message immediately returned, and that is used to know whether the extension exists, and~~ one "add-chain-ok" or "add-chain-error" message. All ~~three~~ two messages indicate which `chainId` they refer to, and "add-chain-error" also provides an `error` string.
Now that we have the `add-chain-ok` message, there is no reason for the `ConnectionManager` to try to handle `RPC` messages that came too early. Instead, now it should send an error to the content-script if an RPC message comes before the `add-chain-ok` message has been sent. Therefore, this logic and the related tests have …
> add `chain-ready` message type

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- Add a new message "remove-chain" that tells the extension that we no longer want a chain. This is equivalent to the legacy `action: "disconnect"`.
> add  `remove-chain` type into `ToExtension`

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
- projects/extension/src/mocks.ts
- Split `ToApplication` and `ToExtension` in multiple messages based on their type, so that `add-chain`, `remove-chain`, etc. can be passed different fields. The `chainId` field shouldn't be directly in `ToApplication` and `ToExtension` but in each individual message.
I initially thought that it would make sense to also get rid of the `parachainSpec` property in this PR, but things started to get a bit out of hand. So, I decided to tackle that in the next PR, as it's very much related to the effort of adding the `potentialRelayChainIds` property into the `add-chain` message.
> improve typings of `ToExtension` & `ToApplication`

- projects/extension/public/manifest.json
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/index.ts
- Add functionality to extension in order to periodically call `client.databaseContent()` for the well-known-chains (`Polkadot`, `Kusama`, `Rococo`, `Westend`) and save the result in local storage, using the chrome feature `alarms`.
- The alarm will repeat every 5 (`periodInMinutes`) minutes after the initial event for DatabaseContentAlarm
- `databaseContent()` is called with `QUOTA_BYTES: 5000000` divided by the amount of known chains (as of now 4). The maximum amount (in bytes) of data that can be stored in local storage, as measured by the JSON stringification of every value plus every key's length.
- Upon init of extension for each chain the `databaseContent` will be retrieved from localStorage and sent to `addChain`
Fixes #568
> Update databaseContent from smoldot to local storage

- packages/connect-extension-protocol/src/index.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.test.ts
- packages/connect/src/ExtensionProvider/ExtensionProvider.ts
- projects/extension/src/background/ConnectionManager.test.ts
- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/content/ExtensionMessageRouter.test.ts
- projects/extension/src/content/ExtensionMessageRouter.ts
I don't really understand why we're using the name `payload` everywhere, while these payload represent different things depending on the message.
> Replace `payload` fields with more accurate names

- packages/connect/extension-resolver.cjs
- packages/connect/src/connector/smoldot-light.test.ts
We have  a somewhat "flaky test" that for some reason it only manifest itself on the CI of GB for node 14... I've been looking a bit into this, and I'm quite confident that it has to do with [this](https://github.com/paritytech/substrate-connect/pull/718#discussion_r802567024). I'm quite confident that these new tests should put an end to this flaky test.
> Improve connector/smoldot-light tests

- packages/connect/src/createScClient/ScProvider/Health.ts
This was modified in https://github.com/paritytech/substrate-connect/pull/737 for no good reason.
The only thing we want to catch is errors in `JSON.parse`. Nothing else. If `requestToSmoldot` throws, we must **not** catch the exception.
> Revert change to health checker made during transfer

- projects/extension/src/background/ConnectionManager.ts
- projects/extension/src/background/index.ts
- projects/extension/src/background/types.ts
- projects/extension/src/components/NetworkTab.tsx
- projects/extension/src/containers/Options.tsx
- projects/extension/src/types/index.ts
I wanted to do this change as part of my ConnectionManager refactor, but I didn't want my first PR to spill over the UI stuff.
This PR removes the usage of the `SmoldotHealth` interface, because the health checker is an implementation detail that has no place in an API.
It also makes the `isSyncing` and `peers` fields non-optional, which is more correct.
> Don't use the `SmoldotHealth` interface from health checker

- packages/connect/src/createPolkadotJsScClient/createPolkadotJsScClient.test.ts
- packages/connect/src/createPolkadotJsScClient/createPolkadotJsScClient.ts
I made a mistake when I tried to tackle the issue with stale subscriptions that remain on the smoldot chain after the chain has changed its status to "syncing". This PR addresses the issue. The list of supported subscription methods was taken from [here](https://github.com/paritytech/smoldot/blob/17425040ddda47d539556eeaf62b88c4240d1d42/src/json_rpc/methods.rs#L338-L462). While reviewing, please ensure that I didn't miss any methods :pray:.
> fix: stale unsubscriptions

- .ensure-resolution.mjs
- .github/workflows/ci.yml
- package.json
Adds a new step in the CI to ensure that we don't accidentally forget to update the `resolutions` entry on the root `package.json`.
> CI: ensure resolutions version matches local version

- packages/connect/CHANGELOG.md
- packages/connect/src/connector/extension.test.ts
- packages/connect/src/connector/extension.ts
`"There was an error creating the smoldot chain."` is not an acceptable error message
> Better error message when extension rejects a chain

- .prettierignore
I've been tweaking my setup to account for the style and formatting changes that have happened in my absence. I hadn't noticed that the `_site` folder wasn't' ignored by prettier when I was making my documentation PR because I wasn't linting.  This stops prettier checking the autogenerated `_site` folder and shouting about lots of issues that we shouldn't care about.
> Prettier ignore generated docs folder

- .github/workflows/update-chain-specs.yml
This change means we can run the periodic spec update workflow from the github actions UI as well as the cron timer running it.  I have created a new `substrate-connect` user in github which I have access to so that I can sign the CLI on behalf of the bot and I have generated a new personal access token from that account and updated the GH_TOKEN secret.  Once this PR is merged I should be able to rerun the workflow from the CI to generate new pull request witha  commit from this new `substrate-connect` user instead of the `mergify` user.
> Allow triggering spec update workflow by github UI

- projects/extension/src/background/ConnectionManagerWithHealth.ts
This also fixes two issues:
- We didn't properly bump `nextRpcRqId` when restarting the subscription.
- We didn't unpin the blocks that were notified to us.
Can be reviewed commit by commit.
I haven't tested whether it works, sorry.
> Add the latest block height to the chain information provided by the manager

- tsconfig.base.json
Remove `declarationMap` that was generating source map for `.d.ts files` which map back to the original .ts source file since we do not ship those `ts` files - which resulted to the error described in #1196. In addition sourceMap was replaced with `inlineSourceMap` in order to avoid similar issues.
Fixes #1196
> Alter base tsconfig in order to avoid missing source map warnings

- .github/workflows/publish.yml
Addresses https://gitlab.parity.io/parity/vulnerability-response/-/issues/50
Quick fix is to pin GHA to specific commit so further possible changes may not affect our setup.
> Pin version of Rober19/compare-npm-versions-ci GHA to specific commit

- projects/extension/src/containers/Options.tsx
Fix bug that was showing all networks and urls under the 1st known network
> Fix how Options Page of extension show networks and app connected to them

- projects/extension/src/components/IconWeb3.tsx
Fixes #1327
Replacing '?' with a more "seal of authenticity" icon (see Westmint chain below):
> Replace '?' with actual icon

- packages/connect/src/connector/extension.test.ts
This test is bogus and it's passing by accident.
As it's explained [in here](https://github.com/paritytech/substrate-connect/blob/3911d973b7e7883f763515ce74a53faaf4048922/packages/connect/src/connector/extension.ts#L180-L185).
> In the situation where we tried to create a well-known chain, the extension isn't supposed to ever return an error. There is however one situation where errors can happen: if the extension doesn't recognize the desired well-known chain because it uses a different list of well-known chains than this code. To handle this, we download the chain spec of the desired well-known chain and try again but this time as a non-well-known chain.
Therefore, we shouldn't have a test that tries to test something that should never happen. What's funny is that the only reason why …
> chore: remove bogus test

- .github/workflows/ci.yml
- .github/workflows/update-chain-specs.yml
GitHub is going to deprecate `save-state` and `set-output` commands. [More info](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
This PR adjusts GHA workflow to use new syntax.
Part of https://github.com/paritytech/ci_cd/issues/805
> CI: fix gha set-output command

- package.json
- packages/connect-extension-protocol/tsconfig-cjs.json
- packages/connect-extension-protocol/tsconfig-mjs.json
- packages/connect-extension-protocol/tsconfig.json
- packages/connect/.eslintignore
- packages/connect/src/connector/extension.test.ts
- packages/connect/src/connector/extension.ts
- packages/connect/src/connector/index.ts
- packages/connect/src/connector/smoldot-light.test.ts
- packages/connect/src/connector/smoldot-light.ts
- packages/connect/tsconfig-cjs.json
- packages/connect/tsconfig-mjs.json
- packages/connect/tsconfig.json
- projects/burnr/tsconfig.json
- projects/demo/tsconfig.json
- projects/extension/tsconfig.json
- tsconfig.base.json
- tsconfig.json
- Add a `tsconfig.base.json` where each workspace extends from it
- set `moduleResolution` to `Bundler` for `projects/*/tsconfig.json`
- Remove root `tsconfig.json` because the project build configurations do not use root `tsconfig.json` references
> feat: simplify `tsconfig.json`

- .github/workflows/ci.yml
- projects/extension/assets/manifest-v2.json
- projects/extension/assets/manifest-v3.json
- projects/extension/package.json
- projects/extension/scripts/generateManifest.js
Use `package.json` version as the source of truth for the `manifest.json` version
> feat: use `package.json` version as the source of truth for the `manifest.json` version

- packages/connect/package.json
- packages/connect/src/connector/smoldot-light.ts
- packages/connect/src/worker-node.ts
- packages/connect/src/worker.ts
Closes https://github.com/paritytech/capi/issues/47
Add `./worker` subpath to `@substrate/connect`.
Then, `@substrate/connect/worker` is a WebWorker that runs smoldot (see [smoldot usage with a web worker](https://smol-dot.github.io/smoldot/doc-javascript/#md:usage-with-a-worker))
Test it with `vite` [WebWorkers](https://v3.vitejs.dev/guide/features.html#web-workers)
```ts
import { createScClient } from "@substrate/connect"
import ScWorker from "@substrate/connect/worker?worker"
createScClient({
embeddedNodeConfig: {
workerFactory: () => new ScWorker(),
},
})
.addWellKnownChain("polkadot", (response) =>
console.log({ response }),
)
.then((chain) => {
chain.sendJsonRpc(
JSON.stringify({
jsonrpc: "2.0",
id: "1",
method: "chainHead_unstable_follow",
params: [true],
}),
)
})
```
Test it with …
> feat: add @substrate/connect/worker

- projects/extension/package.json
The `bundle` script was meant to zip the extension source code.
`yarn pack` does the same thing, so it can be removed.
> chore: remove bundle script

- .github/workflows/zombienet.yml
- Bump zombienet to latest release (v1.3.68)
- Change checks to polkadot SDK (v1.0)
> Bump zombienet to latest release; Change checks to polkadot SDK

- packages/connect/src/connector/smoldot-light.ts
The dynamic import of `smoldot` used on the `smoldot-light.ts` file was pointless due to the fact that the class `QueueFullError` was not being dynamically imported. As a result of this,  all users of `@substrate/connect` end up with the smoldot binary included in the main-bundle of their projects, this is specially annoying for those ones who have the extension installed.
This PR is a pragmatic fix to this issue.
> fix: code splitting problem

- packages/connect/package.json
- projects/extension/package.json
- projects/extension/src/background/addChain.ts
- projects/extension/src/background/index.ts
- projects/extension/src/background/trackChains.ts
- projects/extension/src/background/updateDatabases.ts
- projects/extension/vite.script.config.js
- yarn.lock
Removes `@substrate/connect` lib from the extension because it uses a dynamic import to create the `smoldot` client.
Dynamic imports are not supported in the extension background script ServiceWorker. 
Note: downgraded `smoldot` to `2.0.6` until this [issue](https://github.com/smol-dot/smoldot/issues/1330) is fixed.
> fix(extension): @substrate/connect dynamic import

- .github/workflows/ci.yml
- .github/workflows/deploy-projects-and-docs.yml
- package.json
Rename `pnpm deploy` script to `pnpm deploy-projects-and-docs` 
This is needed because `pnpm deploy` built-in command conflicts with existing NPM scripts named deploy (see [issue](https://github.com/pnpm/pnpm/issues/5163))
> fix: rename deploy script to deploy-projects-and-docs

- packages/secure-storage/src/password.ts
removes the node dependency by using `crypto` (from the browser) instead of `webcrypto` from node.
> fix: remove crypto node dependency in secure local storage

- projects/wallet-template/src/background/createBackgroundRpc.ts
- projects/wallet-template/src/background/types.ts
- projects/wallet-template/src/containers/WalletPopup.tsx
- projects/wallet-template/src/containers/WalletPopup/components/DecodedCallData.tsx
- projects/wallet-template/src/containers/WalletPopup/components/UserSignedExtensionInputs.tsx
> feat(wallet-template): add UserSignedExtensionInputs component

- projects/wallet-template/assets/manifest-v3-chrome.json
- projects/wallet-template/assets/manifest-v3-firefox.json
- projects/wallet-template/src/background/createBackgroundRpc.ts
- projects/wallet-template/src/background/types.ts
- projects/wallet-template/src/containers/WalletPopup.tsx
- projects/wallet-template/src/containers/WalletPopup/components/ProtectedRoute.tsx
- projects/wallet-template/src/containers/WalletPopup/hooks/useKeyring.tsx
- projects/wallet-template/src/containers/WalletPopup/pages/UnlockKeyring.tsx
- projects/wallet-template/src/containers/WalletPopup/pages/Welcome.tsx
Related https://github.com/paritytech/substrate-connect/issues/1992
- browser action icon launches the wallet popup
- if no password has been set, the user is redirected to create the password
- after password creation, redirect to accounts
> feat: setup onboarding routes

- .github/workflows/update-chain-specs.yml
Changes the github token from `GH_TOKEN` to `GITHUB_TOKEN` for deploying change specs. The old token expired and was likely somebody's personal access token. We need a org level solution with signed commits to do this, but for now changing it back to `GITHUB_TOKEN` is sufficient enough to get this working again.
closes: #2078
> fix: chainspec ci

- .github/workflows/update-chain-specs.yml
Now it properly creates a GH issue if the workflow fails.
also uses semantic commits now.
closes: https://github.com/paritytech/substrate-connect/issues/2081
> fix: chain-specs-periodic-update ci

- examples/light-client-dapp/src/App.tsx
- examples/light-client-dapp/src/components/ChainSelect.tsx
- examples/light-client-dapp/src/components/index.ts
- examples/light-client-dapp/src/hooks/useUnstableProvider.tsx
- examples/light-client-dapp/src/settings.ts
Updates the LC Dapp to disconnect the provider when the chain is changed. This is to ensure we don't show the accounts from the old chain.
> feat(lc-dapp): disconnect provider when chain id is changed

- zombienet-tests/src/0002-parachain.toml
Have no idea what "docker.io/paritypr/synth-wave:4131-0.9.12-ccd09bbf-29a1ac18" is ... likely is very outdated. Updating the zombienet test to "docker.io/paritypr/polkadot-debug:master" seems sensible.
> fix(zombienet-tests): update default image

- projects/extension/src/background/heartbeat.ts
- projects/extension/src/background/index.ts
- projects/wallet-template/src/background/heartbeat.ts
- projects/wallet-template/src/background/index.ts
Improves the stability of the extension by ensuring it doesnt shutdown randomly due to the nature of chrome background service worker lifecycle. 
This doesn't fix #1786 but reduces the likelihood of the extension getting stuck in the past.
See: https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers, section: "Keep a service worker alive continuously"
> feat: add heartbeat to background service worker

- README.md
Corepack pulls in the correct pnpm version specified in the package.json to do `pnpm i` etc... this needs to be documented.
> chore(docs): prefix pnpm ops with corepack

- projects/wallet-template/src/components/Layout2.tsx
- projects/wallet-template/src/containers/WalletPopup/pages/CreatePassword.tsx
- projects/wallet-template/src/containers/WalletPopup/pages/Welcome.tsx
Fixes the branding on the welcome and create password pages to match the official substrate branding with the underscore at the end of substrate.
> fix(wallet-template): substrate branding

- pnpm-lock.yaml
- projects/wallet-template/package.json
- projects/wallet-template/src/components/Layout2.tsx
- projects/wallet-template/src/containers/Options.tsx
- projects/wallet-template/src/containers/WalletPopup.tsx
- projects/wallet-template/src/containers/WalletPopup/pages/Accounts/Accounts.tsx
- projects/wallet-template/src/containers/WalletPopup/pages/CreatePassword.tsx
- projects/wallet-template/src/containers/WalletPopup/pages/Welcome.tsx
- Updates the Account page to look better.
- Removes the debug header since it can now be accessed in the Accounts UI under the debug tab
- Adds Typescript 5.5 beta to take advatange of the [type predicate inference feature](https://www.totaltypescript.com/type-predicate-inference), specifically when the accounts are filtered between derivation path based accounts and imported accounts. Before we were writing our own type guards. This release is [almost out](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/), so this addition should be a non-issue.
> feat(wallet-template): accounts ui revamp

- package.json
- pnpm-lock.yaml
Polkadot JS has an optional dependecy on substrate connect that is only used as types. This is causing "older" substrate connect versions and its dependencies to leak into the lockfile which is annoying. 
This change locks the `@substrate/connect` version to the workspace version
```
➜  substrate-connect git:(main) corepack pnpm why -r @substrate/connect
Legend: production dependency, optional only, dev only
@substrate/burnr@0.0.0 /home/ryan/Documents/Repositories/substrate-connect/projects/burnr
dependencies:
@polkadot/api 10.13.1
├─┬ @polkadot/api-augment 10.13.1
│ └─┬ @polkadot/api-base 10.13.1
│   └─┬ @polkadot/rpc-core 10.13.1
│     └─┬ @polkadot/rpc-provider 10.13.1
│       └── @substrate/connect 0.8.8
├─┬ @polkadot/api-base 10.13.1
│ └─┬ @polkadot/rpc-core 10.13.1
│   └─┬ …
```
> fix: force substrate connect version

- zombienet-tests/src/0002-parachain.zndsl
The zombienet tests are flaky and always timeout. This increases the timeout.
> chore(zombienet-tests): increase timeout

- packages/connect-discovery/src/index.ts
- packages/discovery/src/index.ts
- packages/smoldot-discovery/src/types/index.ts
- pnpm-lock.yaml
- projects/wallet-template/package.json
- projects/wallet-template/src/inpage/index.ts
- projects/wallet-template/src/inpage/pjsInject.ts
While working on #2221, I discovered its actually infeasible for the provider in `ProviderDetail`l to be a not declared as a promise.
```diff
export type ProviderDetail = {
kind: string
info: ProviderInfo
-  provider: unknown
+  provider: Promise<unknown>
}
```
This is because the provider is created in the inpage/content-script of the extension which runs at the same time when the dapp loads. So if your only able to create the provider asynchronously, you're out of luck because discovery protocol function `getProviders` will run when the page loads, leading to a race condition.
Hence, I'm changing this back to `Promise<unknown>`, which is what we orignally had before. 
In the wallet-template we invoke `getLightClientProvider` to create the provider which always returns a promise.
We …
> fix: discovery protocol - providers not being async

- package.json
- pnpm-lock.yaml
Smoldot version [getting out of sync](https://github.com/paritytech/substrate-connect/pull/2248) in `light-client-extension-helpers` because of the lockfile is quite frustrating. This because its a [peer dep](https://github.com/paritytech/substrate-connect/blob/main/packages/light-client-extension-helpers/package.json#L40). 
This change forces the smoldot version at the workspace level.
> chore: force smoldot version

- package.json
Removes the `workspaces` field in the package.json. These don't work with pnpm. It was also causing changesets to fail in CI.
> chore: remove workspaces in package.json

- .changeset/tame-tables-share.md
- packages/smoldot-discovery/src/connector.ts
- packages/smoldot-discovery/src/types/index.ts
Re-exports the missing types that are exposed in the public API from @substrate/light-client-extension-helpers/web-page
> fix(smoldot-discovery): re-export missing types

- .changeset/eleven-steaks-attend.md
- packages/smoldot-discovery/package.json
Update the peer dependencies constraint on "@substrate/light-client-extension-helpers since the current constraint confuses changesets and cause it to make a major version bump
> fix(smoldot-discovery): peer dependencies constraint

- .changeset/small-shirts-press.md
- packages/light-client-extension-helpers/README.md
Docs for the newly added tx-helper subpath
see: https://github.com/polkadot-js/extension/pull/1389 for usage
> docs: tx-helper

- .changeset/chatty-eels-taste.md
- examples/light-client-extension-helpers-extension/src/content.ts
- projects/extension/src/content/index.ts
- projects/wallet-template/STEP-BY-STEP-GUIDE.md
- projects/wallet-template/src/content/index.ts
Script should be loaded as `module` to be run in isolated scope.
Fixes #2390
> fix: `inpage.js` script variables leaking into global scope

- .changeset/pink-drinks-matter.md
- packages/light-client-extension-helpers/src/background/background-helper.ts
Fixes an issue where chains connected from dapp would get stuck after smoldot was restarted.
> fix: client getting stuck after smoldot restart

- .changeset/cuddly-apricots-fly.md
- packages/light-client-extension-helpers/package.json
- pnpm-lock.yaml
Types are already re-exported, so this peer dep is useless.
https://github.com/paritytech/substrate-connect/blob/main/packages/light-client-extension-helpers/src/tx-helper/types.ts
> chore(lceh): remove papi peer deps

- .changeset/friendly-toys-remember.md
- .eslintrc.cjs
- packages/connect/src/connector/index.ts
- packages/connect/src/connector/smoldot-light.ts
- packages/connect/src/connector/types.ts
- packages/connect/src/index.ts
- packages/smoldot-discovery-connector/package.json
- packages/smoldot-discovery-connector/src/index.ts
- packages/smoldot-discovery/src/types/index.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- projects/demo/package.json
- projects/demo/src/index.ts
Existing smoldot interface wasnt compatible to the actual smoldot interface, so we couldnt use `smProvider`. 
This change removes the "jsonRpcCallback" from `addChain` and just exposes `nextJsonRpcResponse`and `jsonRpcResponses`, just like smoldot does.
> fix!: make smoldot discovery interface conform to smoldot interface
